package com.floatingbubbleapp;

import android.app.Service;
import android.content.Intent;
import android.graphics.PixelFormat;
import android.os.IBinder;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.MotionEvent;
import android.view.View;
import android.view.WindowManager;
import android.widget.ImageView;

public class FloatingBubbleService extends Service {

    private WindowManager windowManager;
        private View floatingBubbleView;

            @Override
                public void onCreate() {
                        super.onCreate();
                                windowManager = (WindowManager) getSystemService(WINDOW_SERVICE);

                                        floatingBubbleView = LayoutInflater.from(this).inflate(R.layout.floating_bubble, null);
                                                final WindowManager.LayoutParams params = new WindowManager.LayoutParams(
                                                                WindowManager.LayoutParams.WRAP_CONTENT,
                                                                                WindowManager.LayoutParams.WRAP_CONTENT,
                                                                                                WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,
                                                                                                                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,
                                                                                                                                PixelFormat.TRANSLUCENT);

                                                                                                                                        params.gravity = Gravity.TOP | Gravity.LEFT;
                                                                                                                                                params.x = 0;
                                                                                                                                                        params.y = 100;

                                                                                                                                                                windowManager.addView(floatingBubbleView, params);

                                                                                                                                                                        final ImageView bubbleImage = floatingBubbleView.findViewById(R.id.bubble_image);
                                                                                                                                                                                bubbleImage.setOnTouchListener(new View.OnTouchListener() {
                                                                                                                                                                                            private int initialX;
                                                                                                                                                                                                        private int initialY;
                                                                                                                                                                                                                    private float initialTouchX;
                                                                                                                                                                                                                                private float initialTouchY;

                                                                                                                                                                                                                                            @Override
                                                                                                                                                                                                                                                        public boolean onTouch(View v, MotionEvent event) {
                                                                                                                                                                                                                                                                        switch (event.getAction()) {
                                                                                                                                                                                                                                                                                            case MotionEvent.ACTION_DOWN:
                                                                                                                                                                                                                                                                                                                    initialX = params.x;
                                                                                                                                                                                                                                                                                                                                            initialY = params.y;
                                                                                                                                                                                                                                                                                                                                                                    initialTouchX = event.getRawX();
                                                                                                                                                                                                                                                                                                                                                                                            initialTouchY = event.getRawY();
                                                                                                                                                                                                                                                                                                                                                                                                                    return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                        case MotionEvent.ACTION_UP:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Add code to handle bubble click event
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case MotionEvent.ACTION_MOVE:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    params.x = initialX + (int) (event.getRawX() - initialTouchX);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            params.y = initialY + (int) (event.getRawY() - initialTouchY);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    windowManager.updateViewLayout(floatingBubbleView, params);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public IBinder onBind(Intent intent) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public void onDestroy() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        super.onDestroy();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (floatingBubbleView != null) windowManager.removeView(floatingBubbleView);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    